In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
Terminations2023 = pd.read_csv('./Terminations2023MOCK_DATA.csv')

In [3]:
#Checking the data
Terminations2023.head(10)

,employee_id,Job Title,hire_date,employee_status,employee_type,Department,job_level,supervisor_status,union_affiliation,Location,age_group,Race/Ethnicity,Gender,termination_date,termination_type,termination_reason,exit interview completed,last performance rating,new company,rehire eligibility
0,1,Staff Accountant I,3/7/2013,terminated,full-time,Training,staff,Yes,Non-Uion,PA,56-65,Pacific Islander,Female,3/29/2023,retirement,retirement,NaN,NaN,NaN,True
1,2,Senior Financial Analyst,9/20/2003,terminated,contract,Legal,executive,No,Non-Uion,CT,18-25,Hispanic/Latino,NaN,1/23/2023,voluntary,commute to work,True,NaN,Bayer Group,True
2,3,Payment Adjustment Coordinator,4/15/2009,terminated,part-time,Services,management,No,Union,CT,56-65,Hispanic/Latino,Male,7/8/2023,voluntary,relocation,False,5.0,Cartwright-Durgan,False
3,4,Environmental Tech,6/19/1984,terminated,contract,Human Resources,NaN,Yes,Union,MA,56-65,Not Specified,Female,7/21/2023,involuntary,RIF,NaN,5.0,"Davis, Steuber and Ward",False
4,5,Human Resources Assistant III,6/27/1990,terminated,full-time,Business Development,staff,No,Non-Uion,PA,36-45,Black,Male,8/13/2023,retirement,retirement,False,3.0,Metz Group,True
5,6,Human Resources Manager,11/3/2013,terminated,full-time,Product Management,staff,Yes,Union,MA,66+,Pacific Islander,Male,7/20/2023,involuntary,company restructuring,True,5.0,NaN,False
6,7,Senior Developer,1/7/2009,terminated,part-time,Training,NaN,No,Non-Uion,NJ,36-45,NaN,NaN,4/1/2023,voluntary,better opportunity,False,4.0,Wisoky Group,False
7,8,Nuclear Power Engineer,5/13/2014,terminated,full-time,Engineering,NaN,No,Non-Uion,NJ,36-45,Hispanic/Latino,Male,6/2/2023,involuntary,poor performance,False,NaN,Nienow Inc,False
8,9,Nurse Practicioner,11/19/1994,terminated,contract,Accounting,staff,Yes,Union,CT,46-55,Pacific Islander,Male,2/15/2023,retirement,retirement,True,5.0,Schmitt-Kreiger,False
9,10,Operator,11/8/2004,terminated,part-time,Support,management,No,Union,NJ,46-55,Pacific Islander,Female,5/12/2023,voluntary,commute to work,False,1.0,Rempel Group,False

In [4]:
#Looking at the column names
Terminations2023.columns

Index(['employee_id', 'Job Title', 'hire_date', 'employee_status',
       'employee_type', 'Department', 'job_level', 'supervisor_status',
       'union_affiliation', 'Location', 'age_group', 'Race/Ethnicity',
       'Gender', 'termination_date', 'termination_type', 'termination_reason',
       'exit interview completed', 'last performance rating', 'new company',
       'rehire eligibility'],
      dtype='object')

In [10]:
#cleaning the necessary columns
Terminations2023_Cleaned = Terminations2023.rename(columns={"employee_id":"Employee ID", "hire_date":"Hire Date", 
                                                                    "employee_status":"Employee Status",
                                                                    "employee_type":"Employee Type", "job_level":"Job Level", 
                                                                    "supervisor_status": "Supervisor Status","union_affiliation":"Union_Affiliation", 
                                                                    "age_group":"Age Group",
                                                                    #Termination file specific columns
                                                                    "termination_date":"Termination Date", "termination_type": "Termination Type", 
                                                                    "termination_reason":"Termination Reason", "last performance rating":"Last Performance Rating",
                                                                    "exit interview completed":"Exit Interview Completed","new company":"New Company", "rehire eligibility": "Rehire Eligibility"})
#confirming the columm cleaning worked 
Terminations2023_Cleaned.columns

Index(['Employee ID', 'Job Title', 'Hire Date', 'Employee Status',
       'Employee Type', 'Department', 'Job Level', 'Supervisor Status',
       'Union_Affiliation', 'Location', 'Age Group', 'Race/Ethnicity',
       'Gender', 'Termination Date', 'Termination Type', 'Termination Reason',
       'Exit Interview Completed', 'Last Performance Rating', 'New Company',
       'Rehire Eligibility'],
      dtype='object')

In [11]:
#Checking the data
Terminations2023.head(10)

,employee_id,Job Title,hire_date,employee_status,employee_type,Department,job_level,supervisor_status,union_affiliation,Location,age_group,Race/Ethnicity,Gender,termination_date,termination_type,termination_reason,exit interview completed,last performance rating,new company,rehire eligibility
0,1,Staff Accountant I,3/7/2013,terminated,full-time,Training,staff,Yes,Non-Uion,PA,56-65,Pacific Islander,Female,3/29/2023,retirement,retirement,NaN,NaN,NaN,True
1,2,Senior Financial Analyst,9/20/2003,terminated,contract,Legal,executive,No,Non-Uion,CT,18-25,Hispanic/Latino,NaN,1/23/2023,voluntary,commute to work,True,NaN,Bayer Group,True
2,3,Payment Adjustment Coordinator,4/15/2009,terminated,part-time,Services,management,No,Union,CT,56-65,Hispanic/Latino,Male,7/8/2023,voluntary,relocation,False,5.0,Cartwright-Durgan,False
3,4,Environmental Tech,6/19/1984,terminated,contract,Human Resources,NaN,Yes,Union,MA,56-65,Not Specified,Female,7/21/2023,involuntary,RIF,NaN,5.0,"Davis, Steuber and Ward",False
4,5,Human Resources Assistant III,6/27/1990,terminated,full-time,Business Development,staff,No,Non-Uion,PA,36-45,Black,Male,8/13/2023,retirement,retirement,False,3.0,Metz Group,True
5,6,Human Resources Manager,11/3/2013,terminated,full-time,Product Management,staff,Yes,Union,MA,66+,Pacific Islander,Male,7/20/2023,involuntary,company restructuring,True,5.0,NaN,False
6,7,Senior Developer,1/7/2009,terminated,part-time,Training,NaN,No,Non-Uion,NJ,36-45,NaN,NaN,4/1/2023,voluntary,better opportunity,False,4.0,Wisoky Group,False
7,8,Nuclear Power Engineer,5/13/2014,terminated,full-time,Engineering,NaN,No,Non-Uion,NJ,36-45,Hispanic/Latino,Male,6/2/2023,involuntary,poor performance,False,NaN,Nienow Inc,False
8,9,Nurse Practicioner,11/19/1994,terminated,contract,Accounting,staff,Yes,Union,CT,46-55,Pacific Islander,Male,2/15/2023,retirement,retirement,True,5.0,Schmitt-Kreiger,False
9,10,Operator,11/8/2004,terminated,part-time,Support,management,No,Union,NJ,46-55,Pacific Islander,Female,5/12/2023,voluntary,commute to work,False,1.0,Rempel Group,False

In [19]:
Terminations2023_Cleaned['Termination Reason'].value_counts()

Termination Reason
Retirement               165
Company Restructuring     79
Better Opportunity        58
RIF                       51
Manager                   39
personal reasons          30
Poor Performance          27
attendance                24
Career Change             21
misconduct                21
Commute to Work           18
Relocation                17
Name: count, dtype: int64

In [21]:
Terminations2023_Cleaned['Employee Type'] = Terminations2023_Cleaned['Employee Type'].replace({'contract': 'Contract', 'part-time': 'Part-Time', 'full-time': 'Full-Time'})
Terminations2023_Cleaned['Employee Status'] = Terminations2023_Cleaned['Employee Status'].replace({'terminated': 'Terminated'})
Terminations2023_Cleaned['Union_Affiliation'] = Terminations2023_Cleaned['Union_Affiliation'].replace({'Non-Uion': 'Non-Union'})
Terminations2023_Cleaned['Job Level'] = Terminations2023_Cleaned['Job Level'].replace({'management': 'Management', 'executive': 'Executive', 'staff': 'Staff'})

#Promotion File specific columns that require cleaning
Terminations2023_Cleaned['Termination Type'] = Terminations2023_Cleaned['Termination Type'].replace({'retirement': 'Retirement', "voluntary":"Voluntary","involuntary":"Involuntary"})
Terminations2023_Cleaned['Termination Reason'] = Terminations2023_Cleaned['Termination Reason'].replace({'retirement': 'Retirement', "commute to work":"Commute to Work","relocation":"Relocation","company restructuring":"Company Restructuring","poor performance":"Poor Performance",
                                                                                                         "manager":"Manager","better opportunity":"Better Opportunity","career change":"Career Change","personal reasons":"Personal Reasons","attendance":"Attendance","misconduct":"Misconduct"})
Terminations2023_Cleaned.head(20)

,Employee ID,Job Title,Hire Date,Employee Status,Employee Type,Department,Job Level,Supervisor Status,Union_Affiliation,Location,Age Group,Race/Ethnicity,Gender,Termination Date,Termination Type,Termination Reason,Exit Interview Completed,Last Performance Rating,New Company,Rehire Eligibility
0,1,Staff Accountant I,3/7/2013,Terminated,Full-Time,Training,Staff,Yes,Non-Union,PA,56-65,Pacific Islander,Female,3/29/2023,Retirement,Retirement,NaN,NaN,NaN,True
1,2,Senior Financial Analyst,9/20/2003,Terminated,Contract,Legal,Executive,No,Non-Union,CT,18-25,Hispanic/Latino,NaN,1/23/2023,Voluntary,Commute to Work,True,NaN,Bayer Group,True
2,3,Payment Adjustment Coordinator,4/15/2009,Terminated,Part-Time,Services,Management,No,Union,CT,56-65,Hispanic/Latino,Male,7/8/2023,Voluntary,Relocation,False,5.0,Cartwright-Durgan,False
3,4,Environmental Tech,6/19/1984,Terminated,Contract,Human Resources,NaN,Yes,Union,MA,56-65,Not Specified,Female,7/21/2023,Involuntary,RIF,NaN,5.0,"Davis, Steuber and Ward",False
4,5,Human Resources Assistant III,6/27/1990,Terminated,Full-Time,Business Development,Staff,No,Non-Union,PA,36-45,Black,Male,8/13/2023,Retirement,Retirement,False,3.0,Metz Group,True
5,6,Human Resources Manager,11/3/2013,Terminated,Full-Time,Product Management,Staff,Yes,Union,MA,66+,Pacific Islander,Male,7/20/2023,Involuntary,Company Restructuring,True,5.0,NaN,False
6,7,Senior Developer,1/7/2009,Terminated,Part-Time,Training,NaN,No,Non-Union,NJ,36-45,NaN,NaN,4/1/2023,Voluntary,Better Opportunity,False,4.0,Wisoky Group,False
7,8,Nuclear Power Engineer,5/13/2014,Terminated,Full-Time,Engineering,NaN,No,Non-Union,NJ,36-45,Hispanic/Latino,Male,6/2/2023,Involuntary,Poor Performance,False,NaN,Nienow Inc,False
8,9,Nurse Practicioner,11/19/1994,Terminated,Contract,Accounting,Staff,Yes,Union,CT,46-55,Pacific Islander,Male,2/15/2023,Retirement,Retirement,True,5.0,Schmitt-Kreiger,False
9,10,Operator,11/8/2004,Terminated,Part-Time,Support,Management,No,Union,NJ,46-55,Pacific Islander,Female,5/12/2023,Voluntary,Commute to Work,False,1.0,Rempel Group,False
10,11,Media Manager II,12/31/1988,Terminated,Part-Time,Marketing,Management,Yes,Union,PA,56-65,Pacific Islander,Male,10/5/2023,Retirement,Retirement,NaN,3.0,NaN,False
11,12,Help Desk Technician,2/5/1991,Terminated,Full-Time,Sales,NaN,Yes,Non-Union,NJ,56-65,Asian,Female,1/20/2023,Voluntary,Better Opportunity,False,5.0,NaN,True
12,13,Compensation Analyst,7/21/2005,Terminated,Part-Time,Support,Executive,Yes,Non-Union,NJ,46-55,Not Specified,Male,7/31/2023,Voluntary,Career Change,False,1.0,"Kuhic, Streich and Padberg",True
13,14,Programmer I,2/27/1985,Terminated,Part-Time,Support,Management,Yes,Non-Union,NY,36-45,Asian,Female,9/7/2023,Retirement,Retirement,False,3.0,NaN,True
14,15,Senior Sales Associate,4/13/2016,Terminated,Full-Time,Engineering,Executive,No,Union,CT,36-45,Pacific Islander,Male,9/29/2023,Involuntary,Poor Performance,True,5.0,Cruickshank-Lakin,True
15,16,Developer I,5/24/2009,Terminated,Contract,Engineering,Executive,No,Union,NY,36-45,Asian,Female,9/9/2023,Voluntary,Manager,True,4.0,Brown and Sons,True
16,17,Junior Executive,9/9/1986,Terminated,Part-Time,Human Resources,Staff,No,Non-Union,NJ,26-35,Black,Female,6/22/2023,Involuntary,Company Restructuring,False,3.0,"Barton, Purdy and Witting",False
17,18,Librarian,1/14/2015,Terminated,Contract,Human Resources,Management,No,Non-Union,PA,66+,Not Specified,Female,8/7/2023,Retirement,Retirement,True,5.0,"Konopelski, Harvey and Lind",True
18,19,Chemical Engineer,12/29/2020,Terminated,Contract,Product Management,Management,No,Union,PA,36-45,Pacific Islander,Female,7/25/2023,Involuntary,Company Restructuring,False,3.0,Marks-Hintz,False
19,20,Associate Professor,3/10/2020,Terminated,Part-Time,Accounting,Staff,No,Union,CT,46-55,NaN,Male,4/30/2023,Retirement,Retirement,False,3.0,Homenick-Fay,True

In [22]:
Terminations2023_Cleaned['Termination Reason'].value_counts()

Termination Reason
Retirement               165
Company Restructuring     79
Better Opportunity        58
RIF                       51
Manager                   39
Personal Reasons          30
Poor Performance          27
Attendance                24
Career Change             21
Misconduct                21
Commute to Work           18
Relocation                17
Name: count, dtype: int64

In [13]:
# Top 10 New Company
top_prior_company = Terminations2023_Cleaned['New Company'].value_counts().head(10)
print("Top 10 New Company:")
print(top_prior_company)
#Results show that there is no company that associates are leaving to in large groups.

Top 10 New Company:
New Company
Williamson Group          3
Cormier and Sons          2
Monahan Group             2
Bayer Group               1
Corkery Group             1
Wisozk-Corwin             1
Dibbert-Erdman            1
Stracke-Lehner            1
Orn, Fritsch and Hills    1
Padberg Inc               1
Name: count, dtype: int64

In [18]:
Terminations2023_Cleaned['Termination Reason'].value_counts()

Termination Reason
Retirement               165
Company Restructuring     79
Better Opportunity        58
RIF                       51
Manager                   39
personal reasons          30
Poor Performance          27
attendance                24
Career Change             21
misconduct                21
Commute to Work           18
Relocation                17
Name: count, dtype: int64

In [23]:
# Export CSV file
Terminations2023_Cleaned.to_csv('Terminations2023_Cleaned.csv', index=False)